version:  '3'
services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    volumes:
      - ${PWD}/volumes:/home/jovyan/work
      - ${PWD}/volumes/arquivos:/home/jovyan/work/datasets
      - ${PWD}/volumes:/home/jovyan/work/modules
    ports:
      - 8888:8888
    container_name: jupyter_notebook